import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ReactElement } from "react";
import { dir } from "i18next";
import { Toaster } from "@/components/ui/toaster"

const inter = Poppins({ subsets: ["latin"], weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"] });

type RootLayoutProps = { children: ReactElement; params: { lng: string } };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        <Toaster/>
        </body>
        <head>
            <title>DreamFactory</title>
            <link rel="icon" type="image/png" href="/icon.png"/>
        </head>
        </html>
  );
}
