"use client";
import { ParallaxScroll } from "@/components/ui/parallax-scroll";

export function ParallaxScrollDemo() {
  return <ParallaxScroll images={images} />;
}

const images = [
    "/output/cat/cat1.webp",
    "/output/cat/cat2.webp",
    "/output/cat/cat3.webp",
    "/output/cat/cat4.webp",
    "/output/desert/desert1.png",
    "/output/desert/desert2.png",
    "/output/desert/desert3.png",
    "/output/desert/desert4.png",
    "/output/desert/desert5.png",
    "/output/desert/desert6.png",
    "/output/desert/desert7.png",
    "/output/dragon/dragon1.png",
    "/output/dragon/dragon2.png",
    "/output/dragon/dragon3.png",
    "/output/dragon/dragon4.png",
    "/output/dragon/dragon5.png",
    "/output/dragon/dragon6.png",
    "/output/dragon/dragon7.png",
    "/output/dragon/dragon8.png",
    "/output/dragon/dragon9.webp",
    "/output/dragon/dragon10.png",
    "/output/dragon/dragon11.png",
    "/output/dragon/dragon12.png",
    "/output/girl/girl1.png",
    "/output/girl/girl2.png",
    "/output/girl/girl3.png",
    "/output/girl/girl4.png",
    "/output/girl/girl5.png",
    "/output/girl/girl6.png",
    "/output/japan/japan.png",
    "/output/kingandshoes/kingandshoes1.png",
    "/output/kingandshoes/kingandshoes2.webp",
    "/output/kingandshoes/kingandshoes3.webp",
    "/output/kingandshoes/kingandshoes4.webp",
    "/output/kingandshoes/kingandshoes5.webp",
    "/output/lantern/lantern1.webp",
    "/output/lantern/lantern2.webp",
    "/output/lantern/lantern3.webp",
    "/output/lantern/lantern4.webp",
    "/output/lantern/lantern5.webp",
    "/output/snake/snake1.webp",
    "/output/snake/snake2.webp",
    "/output/snake/snake3.webp",
    "/output/snake/snake4.webp",
    "/output/snake/snake5.webp",
    "/output/snake/snake7.webp",
    "/output/snake/snake8.webp",
];
